name: Terraform CI (PR)

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: 'true'
  TF_INPUT: 'false'
  AWS_REGION: eu-central-1

jobs:
  plan:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    environment:
      name: dev
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get changed directories
        id: changed-dirs
        uses: tj-actions/changed-files@v46
        with:
          dir_names: "true"
      - name: Configure python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'
          architecture: 'x64'
      - name: Configure aws sam
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.142.1
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::362976989898:role/aws-tf-infra
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-session
      - name: Starting resources deployment 
        run: |
          for dir in ${{ steps.changed-dirs.outputs.all_changed_files }}; do
            echo "Directory $dir was changed"
            if [[ $dir == 'terraform' ]]; then
              echo "Deploying Terraform code"
              cd ./terraform
              terraform --version
              ls -al
            fi
          done
      - run: echo "Job status is ${{ job.status }}."

